<article class="production-companies box-container">
    <div class="container">
        <header><h3 class="text-center"><a href="#production-companies">Production Companies</a></h3></header>
    </div>
    <main class="container">
        <dl>
            <div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>7 Films</h4></dt><dd>Cape Town, S Africa</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Annex Films</h4></dt><dd>London, UK</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Ayngaran Int</h4></dt><dd>Chennai, India</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>BDI</h4></dt><dd>London, UK<strong></strong></dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Bravo Zulu Films</h4></dt><dd>Los Angeles, USA</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Brian Long Prods</h4></dt><dd>San Francisco, USA</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Bully Pictures</h4></dt><dd>Los Angeles, USA</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Cake Film</h4></dt><dd>Amsterdam, Holland</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Centerline</h4></dt><dd>Raleigh, USA</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Cherub Pictures</h4></dt><dd>Sydney, Australia</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Commercial Head Films</h4></dt><dd>Los Angeles, USA</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Concentrated</h4></dt><dd>Chicago, NY</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Colony Agency Prods</h4></dt><dd>Stockholm, Sweden</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Corra Films</h4></dt><dd>NY, USA</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Cinema Campesinos</h4></dt><dd>London, UK</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Cite Amerique</h4></dt><dd>Montreal, Canada</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Clever Media</h4></dt><dd>London, UK</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>CTN Communications</h4></dt><dd>London, UK</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Duo Films</h4></dt><dd>Los Angeles, USA</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Endemol</h4></dt><dd>Mumbai, India</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Eric Rassmussen Prods</h4></dt><dd>NY, USA</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Euro 1080</h4></dt><dd>Lint, Belgium</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Eyeworks BV</h4></dt><dd>Amsterdam, Holland</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>First Wave</h4></dt><dd>New York, USA</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Fitch Live</h4></dt><dd>London, UK</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Fix Films</h4></dt><dd>New York, USA</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Future View</h4></dt><dd>Washington, USA</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Garage Films</h4></dt><dd>Barcelona, Spain</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Gimmeyawallet Prods/Madventures</h4></dt><dd>Helsinki, Finland</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>G+K Filmproduktions</h4></dt><dd>Frankfurt, Germany</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Grande Large</h4></dt><dd>New York, USA</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Great Guns</h4></dt><dd>London/NY, UK/USA</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Group Films</h4></dt><dd>Barcelona, Spain</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Guadiana Producciones</h4></dt><dd>Madrid, Spain</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>JA Digital</h4></dt><dd>London, UK</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Jack Morton Worlwide</h4></dt><dd>London, UK</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Jarowskij Enterprises</h4></dt><dd>Stockholm, Sweden</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>La Fabrica Films</h4></dt><dd>Miami, USA</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Langbein &amp; Partners</h4></dt><dd>Vienna, Austria</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Lisa Film</h4></dt><dd>Vienna, Austria</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Marv Outfit</h4></dt><dd>London, UK</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Mega Builders/Discovery</h4></dt><dd>Toronto, Canada</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Merchant Cantos</h4></dt><dd>London, UK</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Michael Kenna</h4></dt><dd>USA</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Mjolk</h4></dt><dd>Helsinki, Finland</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>MSLO Prods</h4></dt><dd>NY, USA</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Nant Cyf</h4></dt><dd>Wales, UK</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>New Moon</h4></dt><dd>London, UK</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Next Step Film Produktion</h4></dt><dd>Munich, Germany </dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Nonplus</h4></dt><dd>Vienna, Austria </dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>North Sullivan</h4></dt><dd>Sydney, Australia</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>One Six 7 Prods</h4></dt><dd>London, UK</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Outlaw</h4></dt><dd>London, UK</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Promax Media</h4></dt><dd>Dammam, Saudi Arabia</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Proof Films</h4></dt><dd>NY, USA</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Ray Kay Films</h4></dt><dd>Los Angeles, USA</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Raina + Wilson</h4></dt><dd>Toronto, Canada</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Scott Lowden</h4></dt><dd>Atlanta, USA</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Schierke Photographers</h4></dt><dd>Frankfurt, Germany</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Spike Productions</h4></dt><dd>Guernsey, UK</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Spruce Moose</h4></dt><dd>NY, USA</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Storm Films</h4></dt><dd>London, UK</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Strix TV</h4></dt><dd>Stockholm, Sweden</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Sweet Images</h4></dt><dd>London, UK</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Tangerina Azul</h4></dt><dd>Lisbon, Portugal</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Team Halprin</h4></dt><dd>Los Angeles, USA</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>The Family</h4></dt><dd>Milan, Italy</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>The Film House Group</h4></dt><dd>Miami, USA</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Th1ng</h4></dt><dd>London, UK </dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Telefilm</h4></dt><dd>Moscow, Russia</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Telemaz Commercials</h4></dt><dd>Hamburg, Germany</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>United Colors Prods</h4></dt><dd>Miami, FL</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>Videa</h4></dt><dd>Gavie, Sweden</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Watson-Spierman Prods</h4></dt><dd>NY, USA</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>World TV</h4></dt><dd>London, UK</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box"><dt><h4>White Stuff</h4></dt><dd>London, UK</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Woman</h4></dt><dd>Oslo, Norway</dd><br/></div>
                <div class="col-sm-4 dt-box"><dt><h4>Yash Raj Films</h4></dt><dd>Mumbai, India</dd><br/></div>
            </div><div class="row">
                <div class="col-sm-4 dt-box col-sm-push-4"><dt><h4>Yarche! Prods</h4></dt><dd>Moscow, Russia</dd><br/></div>
            </div>
        </dl>
    </main>
</article>
